### ISSUE TITLE
Change indicator size to dip

### ISSUE THREAD

**Issue by hendrawd** [txusballesteros/welcome-coordinator#11]
I think it is better if the indicator size changed from pixel to dp, so it will be same size across multiple density devices

**Comment by txusballesteros** [comment]
Hi @hendrawd,

At first thanks for your suggestion, but I'm not totally agree with your suggestion because the Pixels is the base measure of all the UI components. I mean, imagine that you are used to use SP (I know that is a bad smell it's only an example) What should I do in this case? Offer a new method to allow the size in SP. No.

Doing a conversion method to transform DP to PX it's really really easy. And IMHO this is the right way.

**Comment by hendrawd** [comment]
You will understand if you see this one. It is the default pixel size that you set(12 and 30)

![screen shot 2016-05-02 at 5 30 25 pm](https://cloud.githubusercontent.com/assets/9481791/14952564/7c8883bc-108b-11e6-9d5a-1d591c8035d0.png)

I already made the fix #12 if you want to implement it

**Comment by hendrawd** [comment]
And this turn out to be small on high density screen
![screen shot 2016-05-02 at 5 44 52 pm](https://cloud.githubusercontent.com/assets/9481791/14952778/a17eeace-108d-11e6-9c4c-870b426fdce2.png)
